name: Me UI deployment

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploying Me Web UI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Installation of dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: badatt.dev
