name: Deployment

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Github pages
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        shell: bash
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::409556541503:role/GithubActionsCIRole
          aws-region: ap-south-2

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Deploy Infrastructure
        run: |
          aws s3 ls

      - name: Bootstrap
        run: npm run bootstrap

      - name: Vet
        run: npm run vet

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: beta.tidy-ui.com
