name: Pull request checks & lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  vetTestCoverage:
    name: vet, test & coverage
    runs-on: ubuntu-latest
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v22.14.0'
          registry-url: https://registry.npmjs.org/

      - name: Bootstrap
        run: npm run bootstrap

      - name: Vet
        run: npm run vet

      - name: Build
        run: npm run build
